version: '3.8'
services:
  rupx-node:
    image: rupaya/rupaya-node:latest
    volumes:
      - ./rupaya:/root/.rupaya
      - ./keystore:/root/.rupaya/keystore:ro
    ports:
      - "${HTTP_PORT:-8545}:8545"
      - "${WS_PORT:-8546}:8546"
      - "${P2P_PORT:-30303}:30303"
      - "${P2P_PORT:-30303}:30303/udp"
    environment:
      - NETWORK_ID=${NETWORK_ID:-499}
      - MINER_ETHERBASE=${MINER_ETHERBASE}
      - UNLOCK_ACCOUNT=${UNLOCK_ACCOUNT}
      - HTTP_CORSDOMAIN=${HTTP_CORSDOMAIN:-*}
      - HTTP_VHOSTS=${HTTP_VHOSTS:-*}
      - HTTP_API=${HTTP_API:-eth,web3,net,debug,txpool,personal}
      - WS_API=${WS_API:-eth,web3,net,debug,txpool,personal}
      - VERBOSITY=${VERBOSITY:-3}
    secrets:
      - account_password
    networks:
      - rupaya-network

networks:
  rupaya-network:
    external: true

secrets:
  account_password:
    file: ./account_password.txt