version: '3'
services:
  rupx-node:
    build: .
    volumes:
      - ./rupaya:/root/.rupaya
      - ./keystore:/root/.rupaya/keystore:ro
    ports:
      - "${HTTP_PORT:-8545}:8545"
      - "${WS_PORT:-8546}:8546"
      - "${P2P_PORT:-30303}:30303"
      - "${P2P_PORT:-30303}:30303/udp"
    environment:
      - NETWORK_ID=${NETWORK_ID:-499}
      - MINER_ETHERBASE=${MINER_ETHERBASE}
      - UNLOCK_ACCOUNT=${UNLOCK_ACCOUNT}
      - ACCOUNT_PASSWORD=${ACCOUNT_PASSWORD}
      - HTTP_CORSDOMAIN=${HTTP_CORSDOMAIN:-https://*.rupaya.io}
      - HTTP_VHOSTS=${HTTP_VHOSTS:-rupaya.io,*.rupaya.io}
      - HTTP_API=${HTTP_API:-eth,net,web3}
      - WS_API=${WS_API:-eth,net,web3}
      - VERBOSITY=${VERBOSITY:-3}
    networks:
      - rupaya-network

networks:
  rupaya-network:
    external: true